# Numpy Random functions

### Random basic

In [ ]:
import numpy as np

In [3]:
a=np.random.random(3)
print(a)

[0.61855625 0.36588311 0.1492574 ]


In [12]:
a=np.random.random((2,3,3))# produce 3 rows with 3 columns random numbers
print(a)

[[[0.06504034 0.29521174 0.78108631]
  [0.78408282 0.97242478 0.61048987]
  [0.16703868 0.20103661 0.02580023]]

 [[0.53141968 0.29592592 0.39742434]
  [0.80176307 0.5739357  0.77198841]
  [0.27398073 0.55784641 0.33108531]]]


### Rand function

In [14]:
b=np.random.rand(3,3)
print(b)
print("*************")
c=np.random.rand(4,3,3)
print(c)

[[0.91795625 0.64068669 0.8625213 ]
 [0.55795244 0.4321249  0.35106893]
 [0.4237965  0.2382899  0.36610382]]
*************
[[[0.2697266  0.52946047 0.82723992]
  [0.95067251 0.36577426 0.13269156]
  [0.36470978 0.161191   0.26142098]]

 [[0.17500397 0.13186929 0.49402178]
  [0.04278621 0.4643309  0.57858359]
  [0.82918689 0.96176072 0.69432725]]

 [[0.85646517 0.92760036 0.95330564]
  [0.32555744 0.12297432 0.44760952]
  [0.68798212 0.15049673 0.35686347]]

 [[0.08112523 0.86835389 0.98927127]
  [0.81922491 0.71086332 0.32627444]
  [0.85846336 0.25502925 0.05960112]]]


In [16]:
d=np.random.randn(3,3)  #n is for negative therefore we have both negative and positive numbers
print(d)

[[ 0.96806434  1.17078802  0.35024364]
 [ 1.7209695   0.40681478 -0.68936928]
 [ 1.76280204  2.8751488   1.56422933]]


In [26]:
e=np.random.randint(1,100)# single integer between given range 1 to 99
print(e)
f=np.random.randint(1,100,size=(3,3))# single integer between given range 1 to 99
print(f)

31
[[33  9 56]
 [22 90 20]
 [18 76 41]]


## random.choice

In [35]:
name_list=['MArk','Tony','Sunny','Ricky','Andy']
g=np.random.choice(name_list)
print(g)
h=np.random.choice(name_list,size=(2,2))#size can be (3,3)
print(h)

Sunny
[['Sunny' 'Andy']
 ['Tony' 'Sunny']]
